name: CMake Windows with Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      

    - name: Install and Run OpenCppCoverage
      run: |
        choco install opencppcoverage
        & "C:\Program Files\OpenCppCoverage\OpenCppCoverage" --sources="${{github.workspace}}\src" --export_type=cobertura ...


    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ${{github.workspace}}/coverage.xml
    - uses: actions/checkout@v3
